name: Deploy a GitHub Pages

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
    
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Preparar archivos
      run: mkdir -p build && cp -r src/* build/
    
    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Subir artefacto
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build

    - name: Deploy
      uses: actions/deploy-pages@v4 